// Font Family
import { Recursive } from 'next/font/google'

// CSS
import './globals.css'

import type { Metadata } from 'next'

const recursive = Recursive({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

interface RootLayoutProps {
	children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
	return (
		<html lang='en'>
			<body className={recursive.className}>
				<header></header>
				{children}
				<footer></footer>
			</body>
		</html>
	)
}
